# Generated by Django 4.0.3 on 2022-04-22 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='source',
            field=models.IntegerField(choices=[(1, 'Custom'), (2, 'Tasty'), (3, 'Urlparse')], default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal_type',
            field=models.IntegerField(choices=[(1, 'Breakfast'), (2, 'Lunch'), (3, 'Dinner'), (4, 'Snack'), (5, 'Brunch')]),
        ),
    ]
