# Generated by Django 4.0.3 on 2022-04-23 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_recipe_source_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fat', models.IntegerField(default=0)),
                ('calories', models.IntegerField(default=0)),
                ('sugar', models.IntegerField(default=0)),
                ('carbohydrates', models.IntegerField(default=0)),
                ('fiber', models.IntegerField(default=0)),
                ('protein', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='recipe',
            name='video_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='nutrition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.nutrition'),
        ),
    ]
